version: "3.8"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_service
        ports:
            - "8080:8080"
        environment:
            DB_URL=
    db:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            
